version: '3.8'

services:
  postgres-db:
    # Puoi scegliere una versione specifica di PostgreSQL (es. pg15, pg14)
    image: pgvector/pgvector:0.8.0-pg17
    container_name: postgres_knowledge_base
    restart: always
    ports:
      # Mappa la porta 5432 del container alla porta 5432 dell'host
      - "5432:5432"
    environment:
      # Queste variabili saranno prese dal tuo file .env
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      # Volume per la persistenza dei dati
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  # Definisce il volume Docker
  postgres_data: