version: '3.8'

services:
  postgres-db:
    image: pgvector/pgvector:pg16 # Puoi scegliere una versione specifica di PostgreSQL (es. pg15, pg14)
    container_name: postgres_knowledge_base
    restart: always
    ports:
      - "5432:5432" # Mappa la porta 5432 del container alla porta 5432 dell'host
    environment:
      POSTGRES_USER: ${DB_USER} # Queste variabili saranno prese dal tuo file .env
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volume per la persistenza dei dati
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: # Definisce il volume Docker